@echo off
REM Portable MSVC Toolchain Activation Script
REM Generated by msvc-kit
REM MSVC: 14.44.35207, SDK: 10.0.26100.0, Arch: x64

setlocal enabledelayedexpansion


REM VC paths
set "VCINSTALLDIR=G:\library\c\msvc_kit\VC"
set "VCToolsInstallDir=G:\library\c\msvc_kit\VC\Tools\MSVC\14.44.35207"
set "VCToolsVersion=14.44.35207"

REM SDK paths
set "WindowsSdkDir=G:\library\c\msvc_kit\Windows Kits\10"
set "WindowsSDKVersion=10.0.26100.0\"
set "WindowsSdkBinPath=G:\library\c\msvc_kit\Windows Kits\10\bin\10.0.26100.0"

REM INCLUDE paths
set "INCLUDE=G:\library\c\msvc_kit\VC\Tools\MSVC\14.44.35207\include"
set "INCLUDE=%INCLUDE%;G:\library\c\msvc_kit\Windows Kits\10\Include\10.0.26100.0\ucrt"
set "INCLUDE=%INCLUDE%;G:\library\c\msvc_kit\Windows Kits\10\Include\10.0.26100.0\shared"
set "INCLUDE=%INCLUDE%;G:\library\c\msvc_kit\Windows Kits\10\Include\10.0.26100.0\um"
set "INCLUDE=%INCLUDE%;G:\library\c\msvc_kit\Windows Kits\10\Include\10.0.26100.0\winrt"
set "INCLUDE=%INCLUDE%;G:\library\c\msvc_kit\Windows Kits\10\Include\10.0.26100.0\cppwinrt"

REM LIB paths
set "LIB=G:\library\c\msvc_kit\VC\Tools\MSVC\14.44.35207\lib\x64"
set "LIB=%LIB%;G:\library\c\msvc_kit\Windows Kits\10\Lib\10.0.26100.0\ucrt\x64"
set "LIB=%LIB%;G:\library\c\msvc_kit\Windows Kits\10\Lib\10.0.26100.0\um\x64"

REM PATH additions
set "PATH=G:\library\c\msvc_kit\VC\Tools\MSVC\14.44.35207\bin\Hostx64\x64;%PATH%"
set "PATH=G:\library\c\msvc_kit\Windows Kits\10\bin\10.0.26100.0\x64;%PATH%"

REM Platform info
set "Platform=x64"
set "VSCMD_ARG_HOST_ARCH=x64"
set "VSCMD_ARG_TGT_ARCH=x64"

REM End local and export variables
endlocal & (
    set "VCINSTALLDIR=%VCINSTALLDIR%"
    set "VCToolsInstallDir=%VCToolsInstallDir%"
    set "VCToolsVersion=%VCToolsVersion%"
    set "WindowsSdkDir=%WindowsSdkDir%"
    set "WindowsSDKVersion=%WindowsSDKVersion%"
    set "WindowsSdkBinPath=%WindowsSdkBinPath%"
    set "INCLUDE=%INCLUDE%"
    set "LIB=%LIB%"
    set "PATH=%PATH%"
    set "Platform=%Platform%"
    set "VSCMD_ARG_HOST_ARCH=%VSCMD_ARG_HOST_ARCH%"
    set "VSCMD_ARG_TGT_ARCH=%VSCMD_ARG_TGT_ARCH%"
)

echo MSVC Toolchain activated (MSVC 14.44.35207, SDK 10.0.26100.0, x64)
